### ISSUE TITLE
关于国际化的建议

### ISSUE THREAD

**Issue by gitHusband** [photondragon/webgeeker-validation#1]
定制$langCodeToErrorTemplates 太麻烦了，我觉得可以这样，你觉得呢？

![image](https://user-images.githubusercontent.com/23734057/54260899-36092480-45a5-11e9-80df-adc14861e4d6.png)

**Comment by photondragon** [comment]
> 定制$langCodeToErrorTemplates 太麻烦了，我觉得可以这样，你觉得呢？
> 
> ![image](https://user-images.githubusercontent.com/23734057/54260899-36092480-45a5-11e9-80df-adc14861e4d6.png)

感谢你的建议。
这个功能现在已经改好了，更新到0.4版就可以使用。用法参考项目readme

**Comment by photondragon** [comment]
@gitHusband 
感谢你的建议。
这个功能现在已经改好了，更新到0.4版就可以使用，用法参考项目readme。
要是觉得好用，帮我安利一下😁

**Comment by gitHusband** [comment]
很好用，我打算用到项目中去，谢谢
