### ISSUE TITLE
不提供默认值的吗？

### ISSUE THREAD

**Issue by pz9042** [photondragon/webgeeker-validation#3]
看了下demo，好像不提供参数的默认值以及对参数进行处理，比如trim等

**Comment by photondragon** [comment]
@pz9042 目前只提供参数验证功能，不提供参数提取功能。而且不管你有多少个参数，都通过一次`Validation::validate()`调用来验证的，就算你把某个参数单独trim了，也没法返回。

你想像的提供默认值或trim的这些功能，是怎么使用的，能给出示例代码吗？

**Comment by pz9042** [comment]
```php
<?php

/**
 * @desc 基础控制器
 */

namespace Common;
use Phalcon\Filter;
class BaseController extends \Phalcon\Mvc\Controller
{
	
	protected $query = null;
	
	protected $post_data = [];
	protected $get_data = [];
	
	protected $hostInfo = null;//当前请求的域名
	
	public function initializeRequest(){
		if( strtoupper( $this ->request ->getMethod() ) == 'POST' ){
		    if( stristr( $this ->request ->getContentType(), 'application/json' ) ){
		        $this ->post_data = $this ->request ->getJsonRawBody( true );
		    }else{
		        $this ->post_data= $this ->post();
		    }
		}
		if( strtoupper( $this ->request ->getMethod() ) == 'GET' ){
		    $this ->get_data= $this ->get();
		}
		$this ->hostInfo = $this ->request ->getScheme().'://'.$this ->request ->getHttpHost();
		$this->view->disable();
		
		return true;
		
    }
    
	
    
    /**
     * @desc 获取get参数
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串例如'string,trim'时采用参数过滤 ，当为数组例如['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月8日 下午10:38:50
     */
    final protected function get(string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false) {
    	$data = array_merge($this->request->getQuery(), $this->dispatcher->getParams());
    	unset( $data['_url'] );
    	return $this->sanitize($data, $name, $filter, $defaultValue, $noRecursive);
    }
    
    /**
     * @desc 获取post参数
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串'string,trim'时采用参数过滤 ，当为数组['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月9日 下午8:40:27
     */
    final protected function post(string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false) {
    	$data = $this->request->getPost();
    	
    	return $this->sanitize($data, $name, $filter, $defaultValue, $noRecursive);
    }
    
    /**
     * @desc 获取post或者get参数
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串例如'string,trim'时采用参数过滤 ，当为数组例如['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月9日 下午9:41:49
     */
    final protected function request(string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false){
    	if (isset($name) && $name !== '') {
    		return $this->post($name, $filter, $defaultValue, $noRecursive) ?? $this->get($name, $filter, $defaultValue, $noRecursive);
    	}
    	return array_merge($this->post(null, $filter, $defaultValue, $noRecursive), $this->get(null, $filter, $defaultValue, $noRecursive));
    }
    
    /**
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串例如'string,trim'时采用参数过滤 ，当为数组例如['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月9日 下午10:43:11
     */
    final protected function json(string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false){
    	$data = $this->request->getJsonRawBody(true);
    	if (!is_array($data)) {
    		return [];
    	}
    	return $this->sanitize($data, $name, $filter, $defaultValue, $noRecursive);
    }
    
    /**
     * @param array $data 数据源
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串例如'string,trim'时采用参数过滤 ，当为数组例如['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月9日 下午8:20:15
     */
    final protected function sanitize(array $data, string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false){
    	$nowFilter = null;
    	if (is_string($filter) && !empty($filter)) {
    		$nowFilter = explode(',', $filter);
    	} else if ($filter !== false) {
    		$defaultFilter = $this->config ->filter->default_filter;
    		$defaultFilter = isset($defaultFilter) ? explode(',', $defaultFilter) : [ ];
    		if (is_array($filter)) {
    			$defaultFilter = array_unique(array_merge($filter, $defaultFilter));
    		}
    		if (!empty($defaultFilter)) {
    			$nowFilter = $defaultFilter;
    		}
    	}
    	if (isset($name) && $name !== '') {
    		if (isset($data[$name]) && $data[$name] !== '') {
    			$data = $data[$name];
    		} else {
    			$data = $defaultValue;
    		}
    	}
    	if (isset($nowFilter)) {
    		if(is_array($data)){
    			foreach ($data as $k => $v) {
    				$data[$k] = is_array($v) ? $this->sanitize($data[$k], null, $filter, $defaultValue, $noRecursive) : $this->filter->sanitize($data[$k], $nowFilter, $noRecursive);
    			}
    		}else{
    		    
    			$data = $this->filter->sanitize($data, $nowFilter, $noRecursive);
    		}
    	}
    	return $data;
    }
   
    
    //对参数进行过滤
    //public function 
    
    /**
     * @desc 参数校验
     */
    public function validateParam( $rules, $data ){
    	$this ->validate ->addRules( $rules );
    	$message = $this ->validate ->validate( $data );
    	if( isset( $message[0] ) ){
    	    //throw new \ErrorException( $message[0] ->getMessage(), -50 );
    	    $this ->appFailReturn( -50, $message[0] ->getMessage() );
    	}
    	
    }
    /**
     * @desc 返回数据
     */
    protected function appSuccessReturn( $data = [], $is_object = false ){
    	$this->response->setContentType('application/json', 'UTF-8');
    	if( $is_object ) $data = (object) $data;
    	$result = [
    		'ret' =>200,
    		'data' =>$data,
    		'message' =>'',
    	    'imageHost' =>IMAGE_DNS,
    	    'serviceTime' =>time(),
    	];
    	$this->response->setJsonContent( $result );
    	$this ->response ->send();
    	exit;
    }
    
    /**
     * @desc 返回数据
     */
    protected function appFailReturn( $ret, $message = '', $data = [], $is_object = 1 ){
    	$this->response->setContentType('application/json', 'UTF-8');
    	if( $is_object ) $data = (object) $data;
    	$result = [
    		'ret' =>$ret,
    		'data' =>$data,
    		'message' =>$message ?: \Common\ResMessage::getMessage( $ret ),
    	    'imageHost' =>IMAGE_DNS,
    	    'serviceTime' =>time(),
    	];
    	$this->response->setJsonContent($result);
    	$this ->response ->send();
    	exit;
    }
}
```

之前用phalcon框架，同时在网上找了个改过的，不过这个好像跟验证确实没什么关系

**Comment by pz9042** [comment]
`<?php

/**
 * @desc 基础控制器
 */

namespace Common;
use Phalcon\Filter;
class BaseController extends \Phalcon\Mvc\Controller
{
	
	protected $query = null;
	
	protected $post_data = [];
	protected $get_data = [];
	
	protected $hostInfo = null;//当前请求的域名
	
	public function initializeRequest(){
		if( strtoupper( $this ->request ->getMethod() ) == 'POST' ){
		    if( stristr( $this ->request ->getContentType(), 'application/json' ) ){
		        $this ->post_data = $this ->request ->getJsonRawBody( true );
		    }else{
		        $this ->post_data= $this ->post();
		    }
		}
		if( strtoupper( $this ->request ->getMethod() ) == 'GET' ){
		    $this ->get_data= $this ->get();
		}
		$this ->hostInfo = $this ->request ->getScheme().'://'.$this ->request ->getHttpHost();
		$this->view->disable();
		
		return true;
		
    }
    
	
    
    /**
     * @desc 获取get参数
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串例如'string,trim'时采用参数过滤 ，当为数组例如['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月8日 下午10:38:50
     */
    final protected function get(string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false) {
    	$data = array_merge($this->request->getQuery(), $this->dispatcher->getParams());
    	unset( $data['_url'] );
    	return $this->sanitize($data, $name, $filter, $defaultValue, $noRecursive);
    }
    
    /**
     * @desc 获取post参数
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串'string,trim'时采用参数过滤 ，当为数组['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月9日 下午8:40:27
     */
    final protected function post(string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false) {
    	$data = $this->request->getPost();
    	
    	return $this->sanitize($data, $name, $filter, $defaultValue, $noRecursive);
    }
    
    /**
     * @desc 获取post或者get参数
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串例如'string,trim'时采用参数过滤 ，当为数组例如['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月9日 下午9:41:49
     */
    final protected function request(string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false){
    	if (isset($name) && $name !== '') {
    		return $this->post($name, $filter, $defaultValue, $noRecursive) ?? $this->get($name, $filter, $defaultValue, $noRecursive);
    	}
    	return array_merge($this->post(null, $filter, $defaultValue, $noRecursive), $this->get(null, $filter, $defaultValue, $noRecursive));
    }
    
    /**
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串例如'string,trim'时采用参数过滤 ，当为数组例如['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月9日 下午10:43:11
     */
    final protected function json(string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false){
    	$data = $this->request->getJsonRawBody(true);
    	if (!is_array($data)) {
    		return [];
    	}
    	return $this->sanitize($data, $name, $filter, $defaultValue, $noRecursive);
    }
    
    /**
     * @param array $data 数据源
     * @param string $name 参数名
     * @param string|array $filter 过滤类型，支持string、trim、absint、int、email、float、int!、float!、alphanum、striptags、lower、upper、url、special_chars
     * 当为false时，不使用默认过滤，当为字符串例如'string,trim'时采用参数过滤 ，当为数组例如['string','trim']时采用参数+默认过滤，当为null等其他值时时采用默认过滤
     * @param mixed $defaultValue 默认值
     * @param bool $noRecursive 不递归过滤（即$data不作为数组循环过滤）
     * @return mixed
     * @author zhaoyang
     * @date 2018年5月9日 下午8:20:15
     */
    final protected function sanitize(array $data, string $name = null, $filter = null, $defaultValue = null, bool $noRecursive = false){
    	$nowFilter = null;
    	if (is_string($filter) && !empty($filter)) {
    		$nowFilter = explode(',', $filter);
    	} else if ($filter !== false) {
    		$defaultFilter = $this->config ->filter->default_filter;
    		$defaultFilter = isset($defaultFilter) ? explode(',', $defaultFilter) : [ ];
    		if (is_array($filter)) {
    			$defaultFilter = array_unique(array_merge($filter, $defaultFilter));
    		}
    		if (!empty($defaultFilter)) {
    			$nowFilter = $defaultFilter;
    		}
    	}
    	if (isset($name) && $name !== '') {
    		if (isset($data[$name]) && $data[$name] !== '') {
    			$data = $data[$name];
    		} else {
    			$data = $defaultValue;
    		}
    	}
    	if (isset($nowFilter)) {
    		if(is_array($data)){
    			foreach ($data as $k => $v) {
    				$data[$k] = is_array($v) ? $this->sanitize($data[$k], null, $filter, $defaultValue, $noRecursive) : $this->filter->sanitize($data[$k], $nowFilter, $noRecursive);
    			}
    		}else{
    		    
    			$data = $this->filter->sanitize($data, $nowFilter, $noRecursive);
    		}
    	}
    	return $data;
    }
   
    
    //对参数进行过滤
    //public function 
    
    /**
     * @desc 参数校验
     */
    public function validateParam( $rules, $data ){
    	$this ->validate ->addRules( $rules );
    	$message = $this ->validate ->validate( $data );
    	if( isset( $message[0] ) ){
    	    //throw new \ErrorException( $message[0] ->getMessage(), -50 );
    	    $this ->appFailReturn( -50, $message[0] ->getMessage() );
    	}
    	
    }
    /**
     * @desc 返回数据
     */
    protected function appSuccessReturn( $data = [], $is_object = false ){
    	$this->response->setContentType('application/json', 'UTF-8');
    	if( $is_object ) $data = (object) $data;
    	$result = [
    		'ret' =>200,
    		'data' =>$data,
    		'message' =>'',
    	    'imageHost' =>IMAGE_DNS,
    	    'serviceTime' =>time(),
    	];
    	$this->response->setJsonContent( $result );
    	$this ->response ->send();
    	exit;
    }
    
    /**
     * @desc 返回数据
     */
    protected function appFailReturn( $ret, $message = '', $data = [], $is_object = 1 ){
    	$this->response->setContentType('application/json', 'UTF-8');
    	if( $is_object ) $data = (object) $data;
    	$result = [
    		'ret' =>$ret,
    		'data' =>$data,
    		'message' =>$message ?: \Common\ResMessage::getMessage( $ret ),
    	    'imageHost' =>IMAGE_DNS,
    	    'serviceTime' =>time(),
    	];
    	$this->response->setJsonContent($result);
    	$this ->response ->send();
    	exit;
    }
}
`

**Comment by photondragon** [comment]
@pz9042 

我写的这个验证库，设计理念跟其它验证库是不一样的，简单说就是验证前不需要做任何初始化，干就行了（全程就只需要调用Validation::validate(...)这一个方法），使用起来是十分方便的。

后面有一个完整接口的示例，你自行体会一下。

一个接口大概包括以下步骤：
1. 参数验证
2. 提取参数
3. 查询数据
4. 构造返回数据
5. 返回数据

trim也好，默认值也罢你可以自己在“提取参数”这一步做，不会有多少代码的。而且这两个功能不太方便在验证库里实现，否则就会失去使用的方便性。

分页获取值班表的接口（用的框架是Laravel）：
```php
    public function getPage(Request $request)
    {
        $params = $request->query();

        // 验证参数
        Validation::validate($params, [
            'offset' => 'Required|IntGe:0',
            'count' => 'Required|IntGeLe:1,200',
            'department_id' => 'IntGe:0',
        ]);

        // 提取参数
        $offset = intval($params['offset']);
        $count = intval($params['count']);
        $departmentId = isset($params['department_id']) ? intval($params['department_id']) : null;

        // 查询数据
        $total = 0;
        $worksheets = Worksheet::getWorksheetsWithOffset($offset, $count, $total, $departmentId);

        // 构造返回数据
        $worksheetInfos = $this->_convertWorksheetsToArrays($worksheets);
        $data = [
            'Worksheets' => $worksheetInfos,
            'total' => $total,
        ];

        // 返回数据
        return [
            'data' => $data,
        ];
    }
```
